// import { Geist, Geist_Mono, Poppins } from "next/font/google";
import TextHeader from "@/components/TextHeader";
import "./globals.css";
// import { Poppins } from "next/font/google";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600"],
// });

export const metadata = {
  title: "Foods Menu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`w-full px-5`}>
        <TextHeader />
        {children}
      </body>
    </html>
  );
}
