"use client";
// import { Geist, Geist_Mono, Poppins } from "next/font/google";
import TextHeader from "@/components/TextHeader";
import "./globals.css";
import { usePathname } from "next/navigation";
// import { Poppins } from "next/font/google";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600"],
// });

// export const metadata = {
//   title: "Foods Menu",
//   description: "Generated by create next app",
// };

const enableNavbar = ["/", "/1", "/2", "/3", "/4"];

export default function RootLayout({ children }) {
  const path = usePathname();
  return (
    <html lang="en">
      <body>
        {enableNavbar.includes(path) == true && <TextHeader />}
        {children}
      </body>
    </html>
  );
}
